version: '3.8'

services:
  db:
    image: postgres:15
    container_name: calorie_db
    environment:
      POSTGRES_DB: calorie_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql.sql:/docker-entrypoint-initdb.d/sql.sql
    networks:
      - task_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calorie_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      args:
        JAR_FILE: target/*.jar
    container_name: calorie_app
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/calorie_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - task_network

networks:
  task_network:
    driver: bridge

volumes:
  db_data:
